source 'https://github.com/CocoaPods/Specs.git'
platform:ios, '8.0'

target “PuzGame” do
 inhibit_all_warnings!        #禁止所有警告
pod 'MLTransition', '~> 2.1.2'#滑动返回
pod 'SDTheme'
pod 'MJExtension', '~> 3.0.15.1'
pod 'MLTransition', '~> 2.1.2'#滑动返回
pod 'Bugly'                    #腾讯bug管理系统
#pod 'KMCGeigerCounter'         #检测app fps是否流畅 左边值越大越不流畅
#pod 'ResearchKit', '~> 1.3.1' #苹果官方的医疗SKD
#pod 'MLTransition', '~> 2.1.2'#滑动返回
#pod 'Canvas', '~> 0.1.2'      #动画
#pod 'ReactiveObjC', '~> 1.0.1' #链式编程
#pod 'YYWebImage'
pod 'Masonry'
end
